version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: java-auth-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mini_auth
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: java-auth-app
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mini_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - APP_OAUTH2_AUTHORIZED_REDIRECT_URIS=http://localhost:8080/oauth2/redirect
    depends_on:
      - db

volumes:
  mysql_data:
