spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/mini_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    oauth2:
      client:
        registration:

          google:
            client-id: ${GOOGLE_CLIENT_ID:placeholder-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:placeholder-secret}
            scope:
              - email
              - profile

          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:placeholder-id}
            client-secret: ${FACEBOOK_CLIENT_SECRET:placeholder-secret}
            scope:
              - email
              - public_profile

server:
  port: 8080

app:

  oauth2:
    authorized-redirect-uris:
      - http://localhost:3000/oauth2/redirect

  jwt:
    secret: "my-very-strong-secret-key-at-least-32-bytes-long-123456"
    private-key-path: classpath:certs/private.pem
    public-key-path: classpath:certs/public.pem
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000